### ISSUE TITLE
Exporting whole level

### ISSUE THREAD

**Issue by ambs** [amidos2006/Mario-AI-Framework#2]
Hi

I am trying to find if there is a function to save the whole level (graphic model) to a .png file.
Is this something already available, or not possible yet?

Thank you

**Comment by amidos2006** [comment]
The framework doesn't support that feature yet, it is in the current plan for future versions to have functions that render an entire level or the current game state. If you need the layout of the original levels, you can check the the video game level corpus repo :)

**Comment by ambs** [comment]
In this case it was for the students to see their whole generated level. I guess they will need to play to see it. Thanks!

**Comment by amidos2006** [comment]
The current level files are in a human-readable format, looking over them will give them the indication but to see in mario visuals they will need to play the level for now. Sorry about that.

**Comment by ambs** [comment]
No problem. :) Thanks!
