### ISSUE TITLE
EOF carriage return required for all levels

### ISSUE THREAD

**Issue by mcgreentn** [amidos2006/Mario-AI-Framework#3]
Right now, you have to manually add a carriage return character to the end of the last line of a level (i.e. a blank line is required on the bottom of the level file). Otherwise, you will get a null pointer exception.

**Comment by lukebiddell** [comment]
This doesn't seem to be the case for me, at least on Debian.

**Comment by woitee** [comment]
I am facing the same issue (on Windows). It may have something to do with git settings (git can convert line endings when pulling/pushing).

Anyway, I feel the best way would be to rewrite the code in such a way that it is oblivious to the line endings in the level formats, and also doesn't require a newline at the end. That shouldn't be that hard.

**Comment by amidos2006** [comment]
That what I am playing to do but got busy, feel free to try to solve that :)

**Comment by lukebiddell** [comment]
I can work on this issue.

**Comment by lukebiddell** [comment]
I'm still unable to reproduce the problem. Could you send me a copy of a level file you're having problems with?

**Comment by woitee** [comment]
Actually, the error happened when I just cloned the repo and ran the PlayLevel.java, so with the lvl-1.txt.

**Comment by lukebiddell** [comment]
It was an issue with how levels were loaded, they were split on /n newlines but windows uses /r/n. Fixed it with #8
